#Test php5.6 and php7.0
language: php
php:
  - 5.6
  - 7.0
  - hhvm
#Allow errors in php7
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
before_script:
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - composer require codeclimate/php-test-reporter --dev
#RunTests
script: php phpunit.phar --configuration phpunit.xml --verbose
#after scripts
after_script:
  - CODECLIMATE_REPO_TOKEN= php ./vendor/bin/test-reporter
#Webhook for Gitter
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
addons:
    code_climate:
        repo_token: 
