#Test php5.6 and php7.0
language: php
php:
  - 5.6
  - 7.0
  - hhvm
#Allow errors in php7
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
before_script:
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
#RunTests
script: php phpunit.phar --configuration phpunit.xml --verbose
#Webhook for Gitter
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5eacb5c124fcb31d1531
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
